/*
 * errcode.h
 *
 *  Created on: 2017年10月19日
 *      Author: linzer
 */

#ifndef __QNODE_INCLUDE_ERRCODE_H__
#define __QNODE_INCLUDE_ERRCODE_H__

#define ERROR_MSG_BUF_SIZE	512

#define ERROR_CODE_OFFSET(base, offset) (base + offset)

#define ERROR_SUCCESS	0x0
#define ERROR_FAILD		0x1

/* base error code */
#define ERROR_BASE					0x0100
#define ERROR_INVAL 					ERROR_CODE_OFFSET(ERROR_BASE, 1)
#define ERROR_AFNOSUPPORT			ERROR_CODE_OFFSET(ERROR_BASE, 2)

/* thread error code */
#define ERROR_THREAD_BASE			0x0200
#define ERROR_THREAD_INIT_FAILD 		ERROR_CODE_OFFSET(ERROR_THREAD_BASE, 1)
#define ERROR_THREAD_START_FAILD 	ERROR_CODE_OFFSET(ERROR_THREAD_BASE, 2)

/* file error code */
#define ERROR_FILE_BASE				0x0300
#define ERROR_OPEN_FAILD 			ERROR_CODE_OFFSET(ERROR_FILE_BASE, 1)
#define ERROR_EISDIR					ERROR_CODE_OFFSET(ERROR_FILE_BASE, 2)

/* net error code */
#define ERROR_NET_BASE				0x0400
#define ERROR_AGAIN 					ERROR_CODE_OFFSET(ERROR_NET_BASE, 1)
#define ERROR_CONNABORTED			ERROR_CODE_OFFSET(ERROR_NET_BASE, 2)
#define ERROR_INTR					ERROR_CODE_OFFSET(ERROR_NET_BASE, 3)
#define ERROR_PROTO					ERROR_CODE_OFFSET(ERROR_NET_BASE, 4)
#define ERROR_PERM					ERROR_CODE_OFFSET(ERROR_NET_BASE, 5)
#define ERROR_MFILE					ERROR_CODE_OFFSET(ERROR_NET_BASE, 6)
#define ERROR_BADF					ERROR_CODE_OFFSET(ERROR_NET_BASE, 7)
#define ERROR_FAULT					ERROR_CODE_OFFSET(ERROR_NET_BASE, 8)
#define ERROR_NFILE					ERROR_CODE_OFFSET(ERROR_NET_BASE, 9)
#define ERROR_NOBUFS					ERROR_CODE_OFFSET(ERROR_NET_BASE, 10)
#define ERROR_NOMEM					ERROR_CODE_OFFSET(ERROR_NET_BASE, 11)
#define ERROR_NOTSOCK				ERROR_CODE_OFFSET(ERROR_NET_BASE, 12)
#define ERROR_OPNOTSUPP				ERROR_CODE_OFFSET(ERROR_NET_BASE, 13)

const char* strerror_tl(int errcode);
#endif /* __QNODE_INCLUDE_ERRCODE_H__ */
